### PR TITLE
Create 2022-09-22-clickyturtle-atUtexas.md

### PR DESCRIPTION
**Pull request by atUtexas**
Hello

### CODE REVIEW

**Review by atUtexas — COMMENTED** [review]
Can I please make a change? I accidentally put the wrong link. Thank you.

**Comment by EnglandHam** [comment]
Hello! Great incorporation of the "for i" function! I think you accidentally put the wrong Trinket link ^^;;

**Comment by atUtexas** [comment]
Hello.
I would like to add the following:
---
layout: Post
Author: atUTexas
Title: "Third Reflection: Mountains"

**Review by EnglandHam — APPROVED** [review]

**Review by atUtexas — COMMENTED** [review]
I made the changes now. ready for review. Thank you.

**Pull request merged**
