### PR TITLE
Created April's So Far Reflection

### PR DESCRIPTION
**Pull request by alm7468**
This is my class reflection, it is still in progress.

### CODE REVIEW

**Review by alm7468 — COMMENTED** [review]
still working

**Comment by alm7468** [comment]
I think I'm done for now.

**Review by haley-triem — COMMENTED** [review]
Looking good! Just some tiny changes:

Line 8 typo: "modify" should be "modified" probably
Line 13 typo: "including" -> "include"
Line 17 optional change: you can put tina.write in the apostrophe brackets to make it look like code

**Review by haley-triem — CHANGES_REQUESTED** [review]
Sending a "request changes" so that I can accept the pull request after; my commentary is the same as above though!

**Review by haley-triem — APPROVED** [review]

**Pull request merged**
