### PR TITLE
Create 2022-12-08-Final-Project-Reflection.md

### PR DESCRIPTION
**Pull request by Stuks**
This is my final project and reflection. 

Please let me know if there are any issues with the embedded codes.. GitHubt and I are not friends. :)

### CODE REVIEW

**Comment by hannahmoutran** [comment]
Hi Frank - looks like a great program!  The title in the pull request is missing .md at the the end, though.  Nice meeting you, have a great break!

**Comment by Stuks** [comment]
@hannahmoutran  Ah, yes of course it is why wouldn't. Thank you for pointing that out.

**Comment by Stuks** [comment]
I think I fixed the issue and added some formating to my final reflection. Thank you again @hannahmoutran , have a great break yourself!! :)

**Comment by hannahmoutran** [comment]
You're welcome, Frank!  Just one more thing, you have to put the .md at the end of the pull request file name.  See you next semester :)

**Comment by Stuks** [comment]
Thanks. I think i got it now.. maybe.

**Pull request merged**
