### PR TITLE
Create 2022-11-03-hyotester-CSV-reflection.md

### PR DESCRIPTION
**Pull request by hyo9292**

### CODE REVIEW

**Comment by hyo9292** [comment]
@manasvini2906 
Hello! Finally, I'm done and published csv assignment. Could you please look at my code and give your comment? and then approve my request! thanks!

**Comment by hyo9292** [comment]
@manasvini2906
Hi!!! I'm still waiting to be approved for my CSV reflection. Can you please check my code and approve my full request?

**Comment by manasvini2906** [comment]
Yes sure i'll do it asap.

**Review by manasvini2906 — APPROVED** [review]
Great reflection! What error type did you get while iterating through 0-20?

**Pull request merged**
