### PR TITLE
Hannah Moutran's Reflection 3 - Clicks Clouds Drawing

### PR DESCRIPTION
**Pull request by hannahmoutran**
This is my latest Trinket.  It is a drawing program that allows the user to make clouds and change the color of the 'sky' in the console.  It was fun to make and I hope fun to use!

### CODE REVIEW

**Comment by haley-triem** [comment]
Hi there! Looking really good! I think you might have forgotten a space after the "#" in "#Drawing the Sky" and in "#Full trinket below:" if you want those to show up as title.

**Comment by haley-triem** [comment]
Another quick thing ... in this paragraph, I think you might have used apostrophes instead of backticks? I was reading the bolded parts below as if they were supposed to be in code format:

The next step was making the ‘**clouds**’ function, which needed x and y for arguments, because wherever the user clicks, those coordinates are where the cloud will begin to be drawn. I put that over in the animations tab, and called it into the main tab at the top of the code: ‘**from animations import clouds**.’ Here’s the cloud function:

**Comment by hannahmoutran** [comment]
> Hi there! Looking really good! I think you might have forgotten a space after the "#" in "#Drawing the Sky" and in "#Full trinket below:" if you want those to show up as title.

Thanks, Haley, changed that one, now on to the next!

**Comment by hannahmoutran** [comment]
Thanks, Haley, I love this, I'm learning good stuff from you! Fixed it :)

**Comment by hannahmoutran** [comment]
Thanks, Haley, that looks so much better!

**Review by haley-triem — APPROVED** [review]
Looks great! Loved your program and reflection :)

**Pull request merged**
