### PR TITLE
Create 2022-11-17-Nemo's-Project-Update:Draft-Interface.md

### PR DESCRIPTION
**Pull request by nemothefish260**
This is an update on my final project, a draft interface and a description of planned milestones for the next few weeks.

### CODE REVIEW

**Review by RosalindBradshaw — CHANGES_REQUESTED** [review]
Nemo, this sounds like a really cute game. I like all the details of the bats and the insects along with the owls and flower pollen too. I'm looking forward to seeing how this develops over the next couple of weeks!

It looks, however, like you forgot to add the "_posts/<Username>/" section to your file name and I think you might want to add hyphens (-) between the words Project Update: Draft Interface.

**Review by RosalindBradshaw — CHANGES_REQUESTED** [review]
This looks better, I see you added the _posts to the filename. But it looks like you're still missing your username in the title. Without it, github won't know who the author of the post is.

**Comment by nemothefish260** [comment]
Thank you. I have made the changes you have requested :)

**Comment by nemothefish260** [comment]
Please see now.

**Review by RosalindBradshaw — APPROVED** [review]

**Comment by nemothefish260** [comment]
Thank you so much <3

**Pull request merged**
