### PR TITLE
Added Nathan's first focused reflection

### PR DESCRIPTION
**Pull request by nathanstern93**

### CODE REVIEW

**Review by unixEnthusiast — CHANGES_REQUESTED** [review]
Hi, please find the comments for the changes required in the YAML metadata

- Remove the angle brackets around the author's name

**Comment by unixEnthusiast** [comment]
That looks good Nathan, I guess we all stumble on the creativity issue. Finding inspiration from University and related topics might be a good idea. Keep going!

**Comment by nathanstern93** [comment]
Thanks for the comments. I think all should be good now on my changed post.

**Review by unixEnthusiast — APPROVED** [review]
Looks good!

**Review by unixEnthusiast — APPROVED** [review]
Looks good!

**Comment by unixEnthusiast** [comment]
Merged to main

**Pull request merged**
