### PR TITLE
2022-09-22-Zheng-Zhong-Reflection-on-the-Class-So-Far.md

### PR DESCRIPTION
**Pull request by Eros11on**
This is my relection on the class so far.

### CODE REVIEW

**Review by mchakerautexas — CHANGES_REQUESTED** [review]
Hi Zheng,
I think you missed out on writing the date in the post's file name. Also, I think it's a good practice to not put spaces in the files name, may I suggest using the `-` (hyphen) as a separator, instead of spaces?

**Comment by mchakerautexas** [comment]
HI! I think you changed the name of the pull request instead of the name of the file itself. Could you please change the file name as well? Thanks!

**Comment by mchakerautexas** [comment]
Almost there... sorry to nag but one last change: The date format should be YYYY-MM-DD so for you it should be 2022-09-22

**Review by JamesAthrun — APPROVED** [review]

**Review by Eros11on — COMMENTED** [review]
I have changed my title

**Comment by eah13** [comment]
Merged with admin override.

**Pull request merged**
