### PR TITLE
created first focused reflection post

### PR DESCRIPTION
**Pull request by martsale**

### CODE REVIEW

**Comment by RosalindBradshaw** [comment]
Excellent code, I'd love to see more options in flavors, or the ability to make more scoops of ice cream!

**Review by inf380pcoder — COMMENTED** [review]
Hi! I think you may need to add quotes to your title in the YAML heading.

**Comment by martsale** [comment]
> Hi! I think you may need to add quotes to your title in the YAML heading.

thanks for catching this! it should be updated now

**Review by inf380pcoder — APPROVED** [review]
Looks great! :)

**Pull request merged**
