### PR TITLE
Created JP's turtle hack reflection post.

### PR DESCRIPTION
**Pull request by jpmartinezutexas**
Created and finished the turtle clicky hack reflection post.

### CODE REVIEW

**Comment by jpmartinezutexas** [comment]
Ready to be reviewed.

**Review by hyo9292 — COMMENTED** [review]
Thank you for sharing your code and looks good!

**Review by hyo9292 — APPROVED** [review]
Merged!!

**Comment by Rowan-Loft** [comment]
Looks good JP. Don't see any issues with the file name, date, etc. Thanks for the code.

**Pull request merged**
