### PR TITLE
Create 2022-09-29-rabouti-first-focused-reflection.md

### PR DESCRIPTION
**Pull request by rabouti**
Still editing!

### CODE REVIEW

**Review by hannahmoutran — CHANGES_REQUESTED** [review]
No worries, who knew that we would have an exercise?  I think you can still edit later!

**Comment by rabouti** [comment]
Hi Hannah. What do you think? Does this make any sense?

**Review by hannahmoutran — COMMENTED** [review]
I love your program!  It's beautiful.  The only thing I can see is that the date in the heading I think should be 2022-09-29?  Great job, let me know if you want me to approve and/or merge it!

**Comment by rabouti** [comment]
> 

Thank you for noticing that! Yes, I'm ready!

**Review by hannahmoutran — APPROVED** [review]
Hi!  I was looking back at this, and realized that the title still needs a little tweaking.  It's a small issue, just that the date is written '2022-09-2'.  I think you're missing a '9' so that it will be '2022-09-29'. I'm just going to approve it because I think it will work and depending upon how today's remote class goes you may need it for the links assignment.  I just thought I'd let you know, so that if you want to you can edit the file and have your partner approve that one so that it'll be in the right spot on the website.

**Comment by rabouti** [comment]
Hi Hannah,

I remade this post and it's already on the class website! This one is old.
You do not need to merge. But thank you, I appreciate you for going back
and checking on this for me!

**Pull request merged**
