### PR TITLE
Hyo's Clicky Turtle

### PR DESCRIPTION
**Pull request by hyo9292**
It was challenging for me, but also really enjoyed!

### CODE REVIEW

**Comment by hyo9292** [comment]
@jpmartinezutexas  Hi, could you please check my code and give me your comment to improve my chicky turtle?

**Review by jpmartinezutexas — APPROVED** [review]
Looks great! Nice job.

**Comment by hyo9292** [comment]
Hi did you complete today’s assignment?

**Comment by hyo9292** [comment]
@jpmartinezutexas @eah13  Hi! Could you please double-check my code? When I checked our website and click Hyo's Clicky Turtle...i can see Feng's Clicky Turtlehack. Could you please let me know how to fix it? thanks!

here is my request in github: https://github.com/inf380p/inf380p.github.io/pull/129/files
here is my code in trinkets: https://trinket.io/library/trinkets/cf663b6257

**Pull request merged**
