### PR TITLE
First Reflection

### PR DESCRIPTION
**Pull request by manasvini2906**

### CODE REVIEW

**Review by alm7468 — DISMISSED** [review]
Your YAML metadata could use another look. For example: using your custom Github name and starting the title with double quotes.

**Review by manasvini2906 — COMMENTED** [review]
Will do, thanks!

**Review by atUtexas — APPROVED** [review]

**Comment by atUtexas** [comment]
I like your reflection.

**Comment by atUtexas** [comment]
You may need to add your GitHub name in the Author section.

**Review by atUtexas — APPROVED** [review]

**Pull request merged**
